apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql8
  template:
    metadata:
      labels:
        app: mysql8
    spec:
      containers:
      - image: mysql:8.0.17
        name: mysql
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: munish1234
        - name: MYSQL_DATABASE
          value: testingdbfor_ase
        - name: MYSQL_USER
          value: mani
        - name: MYSQL_PASSWORD
          value: mani1234
        ports:
        - containerPort: 3306
          name: mysql8