apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-mysql-ase.fullname" . }}
  labels: {{ include "helm-mysql-ase.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "helm-mysql-ase.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}